name: Check Product Availability

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 mins
  workflow_dispatch:

jobs:
  check-products:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PRODUCT_URLS: ${{ secrets.PRODUCT_URLS }} # comma-separated

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run availability checker
        run: python check.py
